{{- $component := "postgres" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $component }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "user-mgmt.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.postgres.replicas }}
  selector:
    matchLabels:
      app: {{ $component }}
  template:
    metadata:
      labels:
        app: {{ $component }}
    spec:
      containers:
        - name: {{ $component }}
          image: {{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_DB
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: {{ .Values.postgres.resources.requests.cpu | quote }}
              memory: {{ .Values.postgres.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.postgres.resources.limits.cpu | quote }}
              memory: {{ .Values.postgres.resources.limits.memory | quote }}
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - $(POSTGRES_USER)
                - -d
                - $(POSTGRES_DB)
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
