apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "user-mgmt.labels" . | nindent 4 }}
spec:
  hard:
    requests.cpu: {{ .Values.resourceQuota.cpu | quote }}
    requests.memory: {{ .Values.resourceQuota.memory | quote }}
    limits.cpu: {{ .Values.resourceQuota.cpu | quote }}
    limits.memory: {{ .Values.resourceQuota.memory | quote }}
