apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "user-mgmt.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secret.postgresUser | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgresPassword | b64enc }}
  POSTGRES_DB: {{ .Values.secret.postgresDb | b64enc }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.secret.postgresUser | b64enc }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secret.postgresPassword | b64enc }}
  JWT_SECRET: {{ .Values.secret.jwtSecret | b64enc }}
