{{- $component := "frontend" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $component }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "user-mgmt.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ $component }}
  template:
    metadata:
      labels:
        app: {{ $component }}
    spec:
      containers:
        - name: {{ $component }}
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: {{ .Values.frontend.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.readinessProbe.periodSeconds }}
