apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-mgmt-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aliesenli/user_mgmt_service_ops.git
    targetRevision: HEAD
    path: helm
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: user-mgmt-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
