namespace: user-mgmt
backend:
  image:
    repository: ghcr.io/aliesenli/user-mgmt-backend
    tag: 449e603de077770ea26bc2ae3e2e7941fa2b0f40
  replicas: 1
  port: 8080
  readinessProbe:
    initialDelaySeconds: 90
    periodSeconds: 10
    failureThreshold: 6
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  hpa:
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70
frontend:
  image:
    repository: ghcr.io/aliesenli/user-mgmt-frontend
    tag: 449e603de077770ea26bc2ae3e2e7941fa2b0f40
  replicas: 1
  port: 3000
  apiUrl: "https://app.aliesenli.com/api"
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
config:
  springJpaHibernateDdlAuto: "update"
  jwtIssuer: "user-mgmt-service"
  jwtExpirationMillis: "3600000"
ingress:
  className: nginx
  host: app.aliesenli.com
moduleService:
  image:
    repository: ghcr.io/aliesenli/module-service
    tag: a21323245018afe874a1e7a82dd9f4f31b3a0343
  replicas: 1
  port: 8000
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"
resourceQuota:
  cpu: "3"
  memory: "3Gi"
